### ISSUE TITLE
MemoryError: std::bad_alloc: cudaErrorMemoryAllocation: out of memory

### ISSUE THREAD

**Issue by ronan222222** [yuvalH9/UMERegRobust#6]
Traceback (most recent call last):
  File "train_coloring.py", line 425, in <module>
    train_one_epoch(epoch, dloader_train, model, point_wise_loss_fn, optimizer, summary_writer)
  File "train_coloring.py", line 44, in train_one_epoch
    src_feat = torch.stack(model(src_stensor).decomposed_features, dim=0)
  File "/home/yrn/anaconda3/envs/peizhui/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yrn/UMERegRobust-master/models.py", line 557, in forward
    out_s1 = self.conv1(x)
  File "/home/yrn/anaconda3/envs/peizhui/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yrn/anaconda3/envs/peizhui/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 314, in forward
    outfeat = self.conv.apply(
  File "/home/yrn/anaconda3/envs/peizhui/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 72, in forward
    return fw_fn(
MemoryError: std::bad_alloc: cudaErrorMemoryAllocation: out of memory

Could you help tell me what's going on?

**Comment by yuvalH9** [comment]
Hi @ronan222222,

This error is related to the Minkowski Enginen that can occur due to wrong installation in your venv.
I recommend you to follow the installation instructions in the official repository [Here](https://nvidia.github.io/MinkowskiEngine/overview.html#installation).

I also remember that once I got similar error after long training. I randomly overcome by changing the Random Seed in the beginning of the training code - not absolute sure if this what solved the problem but you can give it a chance.

Good Luck
Yuval
